name: Sync Repositories

on:
  push:
    branches:
      - main
    paths:
      - 'steps/**'
      - 'static/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tablab-steps
      uses: actions/checkout@v4
      with:
        ref: "main"
        path: "tablab-steps"
        token: ${{ secrets.GIT_TOKEN }}

    - name: Checkout steps
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.REPOSITORY }}
        ref: "public"
        path: "steps"
        token: ${{ secrets.GIT_TOKEN }}

    - name: Sync changes to repository steps
      env:
        TOKEN: ${{ secrets.GIT_TOKEN }}
        REPOSITORY: ${{ secrets.REPOSITORY }}
      run: |
        cp -R ./tablab-steps/steps/* ./steps/steps/
        cp -R ./tablab-steps/static/images/* ./steps/static/images/learning/
        
        cd ./steps
        git config user.name github-actions
        git config user.email github-actions@github.com

        git add .
        git commit -m "Steps merged from public repository"
        git push https://x-access-token:${TOKEN}@github.com/${REPOSITORY}.git public

